### ISSUE TITLE
Switches on Popovers not clickable

### ISSUE THREAD

**Issue by ericjiang97** [bumbag/bumbag-ui#10]
Switches on popovers are not clickable via mouse

```
          <Popover.State placement="bottom-end">
            <Popover.Disclosure use={Button}>

            </Popover.Disclosure>
            <Popover title={user ? `Welcome ${user.displayName}` : 'Login to Continue!'} usePortal>
              <Heading use="h6">User Settings</Heading>
              <Switch
                label={`${isLightMode ? 'Light' : 'Dark'} Mode`}
                checked={isLightMode}
                onClick={() => {
                  if (isLightMode) {
                    setColorMode('dark');
                  } else {
                    setColorMode('light');
                  }
                }}
              />
              <hr />
            </Popover>
          </Popover.State>
```

![image](https://user-images.githubusercontent.com/5687681/89287892-13931200-d698-11ea-9b31-c0a1d8ebf80e.png)

You can still toggle it via the spacebar when selected

**Comment by jxom** [comment]
Hmm, can you reproduce this in Playroom? It seems to work for me.
https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8AFCAHCA3GAnAdAMoAuAhsTAHwA6AdgAT2obZ74AiAlgM5gA2EbgFdcMekO4wAvMABCQ4sQi0AvpQDy6GAzSYcuJAHpdrAl14DhomgyYn9NxowDqAC3L0A7qW71irsQAjGG5iP1dOWgBzcI93dC1aGCg-CHoATwghVKhSdIB%2BOicmQk9OYjBXej5SYL4pahAAFQgoqL4xAFsxXFa8AEJG%2BkNHJmMWBzojezYScioQFSA

**Comment by ericjiang97** [comment]
Unfortunately I can't reproduce in playroom, i will debug further.

Line in question is here: https://github.com/ericjiang97/nextjs-personal/blob/feat/firebase/components/nav.tsx#L57

**Comment by ericjiang97** [comment]
Whoops my fault... just realised its onChange not onClick lol
