### ISSUE TITLE
Don't use fixed versions of dependencies

### ISSUE THREAD

**Issue by geakstr** [bumbag/bumbag-ui#105]
While it's a good practice to use fixed versions of dependencies in _applications_, it's very bad for _libraries_, because it produces a lot of duplications with the same app's deps but different versions

https://github.com/bumbag/bumbag-ui/blob/2250c4a6fa2828582ed6fe671d698490915b7b85/packages/bumbag/package.json#L22-L39

I use Duplicates plugin for webpack from https://www.npmjs.com/package/inspectpack package to detect this kind of issues. 

For example in my project I use `"lodash": "4.17.21"` version and bumbag uses `"lodash": "4.17.20"` and webpack resolver should bundle two versions. Duplicates plugin says about it:

```
lodash (Found 2 resolved, 2 installed, 2 depended. Latest 4.17.21.)
  4.17.20 ~/bumbag/~/lodash
    prjct@1.0.0 -> bumbag@1.7.5 -> lodash@4.17.20
  4.17.21 ~/lodash
    prjct@1.0.0 -> lodash@4.17.21
```

For sure I can downgrade lodash, but plugin also reports things I can't fully understand, looks like duplications happen even in bumbag itself

```
@emotion/is-prop-valid (Found 2 resolved, 3 installed, 3 depended. Latest 0.8.8.)
  0.8.2 ~/bumbag/~/@emotion/is-prop-valid
    prjct@1.0.0 -> bumbag@1.7.5 -> @emotion/is-prop-valid@0.8.2
  0.8.8 ~/@emotion/styled-base/~/@emotion/is-prop-valid
    prjct@1.0.0 -> bumbag@1.7.5 -> @emotion/styled@10.0.27 -> @emotion/styled-base@^10.0.27 -> @emotion/is-prop-valid@0.8.8
  0.8.8 ~/@linaria/react/~/@emotion/is-prop-valid
    prjct@1.0.0 -> @linaria/react@3.0.0-beta.1 -> @emotion/is-prop-valid@^0.8.8
```

The solution is to use packages versions ranges for all production deps in bumbag, something like `"lodash": "^4.17.0"` should resolve lodash issue. The same for other deps. I'll try to fork bumbag and do this and check if it helps

**Comment by geakstr** [comment]
Just tried with `"lodash": "^4.17.20"`, got the same results :-\ So my assumption about the fix was wrong

**Comment by jxom** [comment]
Hmm, yeah, we did have non-fixed versions previously a few months ago, however I remember that causing a lot of issues for some of our consumers. I can't remember the reason why, but I think it may have been along the lines of a dependencies introducing a breaking changes downstream. Might revisit this a bit later.
