### ISSUE TITLE
Remember scroll position in docs

### ISSUE THREAD

**Issue by Cyber3x** [bumbag/bumbag-ui#11]
Could you change the docs so when you click on something that's at the bottom of the sidebar the scroll doesn't reset?

**Comment by leonardodino** [comment]
also: the bottom of the scroll area of the sidebar is outside the browser viewport 😄
(maybe should be a separate issue? 🤔)

---

PS: this is such an amazing project 🤩 thanks so much for doing and sharing it @jxom!
really looking forward to an opportunity to use 💯
