### ISSUE TITLE
Component style reset by bb-Box when NODE_ENV=production

### ISSUE THREAD

**Issue by sam-chuang** [bumbag/bumbag-ui#113]
**Component style reset by bb-Box when NODE_ENV=production**

After this [change](https://github.com/bumbag/bumbag-ui/commit/2725b38057fda138a609d914d5e06b09818f8ded#diff-224fe55c8b1ecf26edd3b57ac1cdcf71c3dc29d3f61fc4566d86b1938f162a7d), the order of bb-Box moved to the bottom, according to [this](https://css-tricks.com/precedence-css-order-css-matters/), it reset components' style

Refer to the [repo](https://github.com/sam-chuang/react-bumbag-sandbox)

1. Go to this [link](https://sam-chuang.github.io/react-bumbag-sandbox/)
2. The style of the button got reset by bb-Box

**Expected behavior**
Button's style should based on bb-Box, not reset by bb-Box

**Screenshots**
![button](https://user-images.githubusercontent.com/33828310/112087720-71de1800-8bc9-11eb-8a08-896674806b34.png)

**Device information (please complete the following information):**

-   Device: 
-   OS, version: Win 10
-   Browser, version: Chrome 89

**Comment by jxom** [comment]
Hmm, that's annoying! After our upgrade to Emotion 11, it seemed to have messed up the precedence of the inherited `Box` styles. However, it looks like here that the change I made to move the reset styles to the global styles doesn't seem to work. 
Let me have a look into it.

**Comment by jxom** [comment]
This should be fixed in `1.11.5`

**Comment by sam-chuang** [comment]
Thanks for the fix!!
