### ISSUE TITLE
I seeing more then one lack, I need more feature and fixed system

### ISSUE THREAD

**Issue by meftunca** [bumbag/bumbag-ui#12]
to summarize briefly

- [ ] Components transition property is missing
- [ ] styled to jss (in my opinion)
- [ ] List component 
- [ ] Time/Date picker with range and default feature
- [ ] Project based localization library (declare to react-i18next)

If necessary, I can support you by participating in your project.

Note: Meanwhile, my knowledge of English is insufficient. :)

**Comment by bmartin1134** [comment]
Time and Date picker seconded as essential.

**Comment by jxom** [comment]
> Components transition property is missing

Not sure what you mean here.

> styled to jss (in my opinion)

Why?

> List component

There already is one. https://bumbag.style/typography/list/

> Time/Date picker with range and default feature

This is on the roadmap. https://github.com/bumbag/bumbag-ui/projects/1

> Project based localization library (declare to react-i18next)

I don't see why we would implement i18n into a region agnostic UI library?
