### ISSUE TITLE
Switching to dark mode on Bumbag documentation doesn't update palette colour codes

### ISSUE THREAD

**Issue by emgoto** [bumbag/bumbag-ui#2]
e.g. `Text400` is always `#2e2e2e` even though the color changes.

![Screenshot 2020-07-20 at 2 04 56 pm](https://user-images.githubusercontent.com/33337378/87898645-184da880-ca92-11ea-8640-b471d8c81b48.png)
![Screenshot 2020-07-20 at 2 04 50 pm](https://user-images.githubusercontent.com/33337378/87898649-1a176c00-ca92-11ea-8b8c-4cf487be9d17.png)

**Comment by jxom** [comment]
Thanks for pointing this out!

**Comment by joshuacrowley** [comment]
I think I've got a fix for this #116
