### ISSUE TITLE
Pagination not using the available space when having wide columns

### ISSUE THREAD

**Issue by DarkSmile92** [bumbag/bumbag-ui#29]
**Describe the bug**

As soon as the content of a `Table.Cell` gets wider than 11 characters, the `Pagination` in the footer will collapse and display a mobile version where the last elements are pushed into a new line for every resolution bigger than 375px.

**To Reproduce**

See this [Playroom example](https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8AFAhgcxgYQgOwBcZCA%2BAHTwAJKkAVNAIwBsZKA3NAJwEs1CBeMiADOACzRQIAdxhQhlbsIBKMYQAd8w7m1bjhAEW3dYnYeSrVLdRiwB0ACRgTzl1zXrMYtpdJLXPDk5Q2DBMTCSOEgCMSAD0HnaRwaHh-olBIWERQQBMcQleSZmpBYESxdkSAMz5NoUZKX7xdd6%2BFK61AUkuVqUAQtAAnj0dpT5SI27uLRVgANaSABwA7IPLUjlMAGbCAAzLu1WLaJgEYIsAHp12Fe1T0wEVMDqEAPKcGGgAchAE3GAwa5eW4WKZpYGNACCUCglAgnEonBgAFsIDpKGBxJw0GAiKZKPYAKJKQkAQiBthBYOaAXGk2o4NaEzu90ZswWEBWaw22z2ByOJwwZ0uFKprNKTxeBHenx%2BfwBosaLLcbMawggyNYOlsiqyyoZNLsdOVFIGUGGJtKADEIL96Q8jW1QWD0BhuHg0H98BiAK6cJGEV0wfjAKIAX0oeB9yIYME4ry2QeEIaiuzDeBgFwItEzBEEIC%2BABPMcIiJQAMowbhEIQUMgEev1tRItjcCA%2B4Q5rP5gBq8NEce4WArVZrIDrDcnzZgGi0XrwXbzQjY%2BHksXtFONzopNrtdyB5jiQdwhGIBBIIDDQA)

Change the text of the last column to be shorter or longer and see the result.

**Expected behavior**
The `Pagination` element would use the full width and only push the last elements to a new line if the space is not enough. This is correct for any resolution below 375px.

**Screenshots**
Actual:

![image](https://user-images.githubusercontent.com/10928916/89935166-08992e00-dc12-11ea-86bb-e6303980a6a0.png)

Expected:
![image](https://user-images.githubusercontent.com/10928916/89935201-1a7ad100-dc12-11ea-9783-68ea367337f8.png)

**Comment by jxom** [comment]
I think wrapping it in a `Table.Cell` would fix the issue: https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8AFAhgcxgYQgOwBcZCA%2BAHTwAJKkAVNAIwBsZKA3NAJwEs1CBeMiADOACzRQIAdxhQhlbsIBKMYQAd8w7m1bjhAEW3dYnYeSrVLdRiwB0ACRgTzl1zXrMYtpdJLXPDk5Q2DBMTCSOEgCMSAD0HnaRwaHh-olBIWERQQBMcQleSZmpBYESxdkSAMz5NoUZKX7xdd6%2BFK61AUkuVqUAQtAAnj0dpT5SI27uLRVgANaSABwA7IPLUjlMAGbCAAzLu1WLaJgEYIsAHp12Fe1T0wEVMDqEAPKcGGgAchAE3GAwa5eW4WKZpYGNACCUCglAgnEonBgAFsIDpKGBxJw0GAiKZKPYAKJKQkAQiBthBYOaAXGk2o4NaEzu90ZswWEBWaw22z2ByOJwwZ0uFKprNKTxeBHenx%2BfwBosaLLcbMawggyNYOlsiqyyoZNLsdOVFIGUGGJtKADEIL96Q8jW1QSqJSkMRAmABlNR8fjAKoAX3tKvQGG4eDQf3wGIArpwkYRQzA-VEA5Q8DHkQwYJxXlsk8IU7sA3gYBcCLQywRBCAvgATzHCIiUT0wbhEIQUMgEbvdtRItjcCAx4SV8s1gBq8NEOe4WBbbY7IC7PdX-ZgGi0UbwY%2BrQjY%2BHksWDNENEL1zoNYydHTPthtdruQPMcSTuEIxAIJBAAaAA
