### ISSUE TITLE
`SelectMenu — hasTags` lets you select the same tag twice

### ISSUE THREAD

**Issue by nonissue** [bumbag/bumbag-ui#32]
When using SelectMenu with hasTags, you can select the same tag twice, and it will be added to the 'value' state variable where user selected tags are stored. 

Example:
<img width="759" alt="apw-cat local -  2020-08-12 at 2 30 51 AM" src="https://user-images.githubusercontent.com/5218392/89993383-def8fa80-dc43-11ea-9b65-a393d47ce75b.png">

With a Tag Selection Component, it should only allow you to add each option to your selection once to prevent confusion from a user perspective. Adding a duplicate tag also causes a react dom warning, because you end up with two children (the selected tags) that share an identical key. 

### React-dom warning (truncated):

```js
[Error] Warning: Encountered two children with the same key, `3`. 
Keys should be unique so that components maintain their identity across updates.
Non-unique keys may cause children to be duplicated and/or omitted — 
the behavior is unsupported and could change in a future version.
    in div (created by ForwardRef(Box))
    in ForwardRef(Box)
    in Unknown (created by Set)
    in Set (created by SelectMenuTags)
    in div (created by ForwardRef(Box))
    in ForwardRef(Box)
    in Unknown (created by Box)
    in Box (created by SelectMenuTags)
    in SelectMenuTags
    in div (created by ForwardRef(Box))
    in ForwardRef(Box)
    in Unknown (created by DropdownMenu.Popover)
    in DropdownMenu.Popover
    in div (created by ForwardRef(Box))
    in ForwardRef(Box)
    in Unknown (created by SelectMenu)
    in SelectMenu (at Tags.js:19)
    in Tags (at pages/index.js:16)
    in div (created by ForwardRef(Box))
```

**Expected behavior**

A tag should only be allowed to be selected once

**Possible Solution**

Use a set for storing the selected tags? There may be some gotchas I'm missing, but it might work.

**Device information (please complete the following information):**

-   Device: Macbook Pro, 2015
-   OS, version: macOS 10.15.6
-   Browser, version: Safari 14 TP, Firefox

**Comment by jxom** [comment]
Fixed on `1.0.11`
