### ISSUE TITLE
Enhance typescript type for better autocompletion.

### ISSUE THREAD

**Issue by sondh0127** [bumbag/bumbag-ui#34]
**Is your feature request related to a problem? Please describe.**

### Multiple type definitions of Component props.

For example `onChange` props of `Input` component

![Screenshot from 2020-08-12 14-08-33](https://user-images.githubusercontent.com/62163604/90043472-5b4c1600-dcf6-11ea-956c-4a39666bbc1a.png)

The Input props:
`export type InputProps = BoxProps & LocalInputProps;
`
There are two type of `onChange` from `BoxProps` and `LocalInputProps`

This will make typescript confuse about autocompletion.
![Screenshot from 2020-08-12 23-24-29](https://user-images.githubusercontent.com/62163604/90043900-fe9d2b00-dcf6-11ea-84de-7055857c516b.png)

**Describe the solution you'd like**
Remove duplication type from inheritance props (BoxProps)
```
type IntersectionType = keyof LocalInputProps & keyof BoxProps;

export type InputProps = Omit<BoxProps, IntersectionType> & LocalInputProps;
```

Result: 
![Screenshot from 2020-08-12 23-23-31](https://user-images.githubusercontent.com/62163604/90043971-1bd1f980-dcf7-11ea-8544-e75e3132ae2e.png)

**Additional context**
Another issue related to the literal string union ("circle"). 

![Screenshot from 2020-08-12 23-44-05](https://user-images.githubusercontent.com/62163604/90044027-3c01b880-dcf7-11ea-9e4a-d2ce3a86ac7b.png)

There are no options for Intellisense: 
![Screenshot from 2020-08-12 23-45-41](https://user-images.githubusercontent.com/62163604/90044100-589df080-dcf7-11ea-84cb-06532f958568.png)

Solution and result:
Use simple hack from community

![Screenshot from 2020-08-12 23-56-46](https://user-images.githubusercontent.com/62163604/90044229-8be07f80-dcf7-11ea-8e77-c089c7b9daaa.png)

![Screenshot from 2020-08-12 23-56-28](https://user-images.githubusercontent.com/62163604/90044223-8aaf5280-dcf7-11ea-915c-74ad89ec1465.png)

**Comment by jxom** [comment]
Oh, I love the hack for the avatar... We could easily extend this to other props too, such as `palette`, `variant`, `fontSize`, and other CSS props

**Comment by jxom** [comment]
Fixed on `1.0.12`

**Comment by sondh0127** [comment]
> Oh, I love the hack for the avatar... We could easily extend this to other props too, such as `palette`, `variant`, `fontSize`, and other CSS props

Great work. Keep it up!. I  will report the missing prop options from my explore experience here.

##  CSSProperties
All of CSS properties type need a better type rather than:
```
alignContent?: string | number | { [key: string]: string };
```
Using csstype^3.0.x like this:
```
import * as CSS from 'csstype';
alignContent?: CSS.Property.AlignContent
```
Result:
![Screenshot from 2020-08-13 19-33-30](https://user-images.githubusercontent.com/62163604/90134821-f5b26500-dd9b-11ea-87b6-02ef01dfa694.png)

**Comment by sondh0127** [comment]
##  CSSProperties
All of CSS properties type need a better type rather than:
```
alignContent?: string | number | { [key: string]: string };
```
Using csstype^3.0.x like this:
```
import * as CSS from 'csstype';
alignContent?: CSS.Property.AlignContent
```
Result:
![Screenshot from 2020-08-13 19-33-30](https://user-images.githubusercontent.com/62163604/90134821-f5b26500-dd9b-11ea-87b6-02ef01dfa694.png)

**Comment by sondh0127** [comment]
## Button
`variant` should be omitted from Box and become union:
`variant?: 'default' | 'outlined' | 'ghost' | 'link' | (string & {});`

**Comment by sondh0127** [comment]
## ColorMode
Explicit type for ColorModeContext
`export const ColorModeContext = React.createContext<any>({ setColorMode: () => {}, colorMode: 'default' });`
