### ISSUE TITLE
Rename MenuDisclosure to MenuButton

### ISSUE THREAD

**Issue by b-gibbs** [bumbag/bumbag-ui#37]
Autosuggest produces a warning and an error:

`MenuDisclosure` has been renamed to `MenuButton`. Using `<MenuDisclosure />` will no longer work in future versions. 
 See https://reakit.io/docs/menu

Uncaught TypeError: element.focus is not a function
    onMouseDown Dialog.js:65
    useDisclosureRef Dialog.js:69
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 4
    unstable_runWithPriority scheduler.development.js:653
    React 25
    parcelRequire<["App.js"]< App.js:22
    newRequire App.d36a57b6.js:47
    parcelRequire App.d36a57b6.js:81
    <anonymous> App.d36a57b6.js:120
Dialog.js:65:14
    onMouseDown Dialog.js:65
    (Async: EventListener.handleEvent)
    useDisclosureRef Dialog.js:69
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 3
    performSyncWorkOnRoot self-hosted:1218
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:653
    React 6
    bind_applyFunctionN self-hosted:1369
    dispatchDiscreteEvent self-hosted:1332
    React 19
    parcelRequire<["App.js"]< App.js:22
    newRequire App.d36a57b6.js:47
    parcelRequire App.d36a57b6.js:81
    <anonymous> App.d36a57b6.js:120

**Comment by jxom** [comment]
Fixed in `1.1.2`. Let me know if it works!

**Comment by jxom** [comment]
Looks like the latter error (`Uncaught TypeError: element.focus is not a function`) still exists in Firefox. Tracking the issue here: #33
