### ISSUE TITLE
Add example to docs of usage of both PageWithHeader and PageWithSidebar

### ISSUE THREAD

**Issue by emgoto** [bumbag/bumbag-ui#39]
**Is your feature request related to a problem? Please describe.**

When trying to use both `PageWithHeader` and `PageWithSidebar`, I'm noticing that the sidebar cuts off the bottom pixel of the header:

[Playroom example](https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8AFAhgcxgdQJYBcALACRjVgCcAdAOwAI7CzLTcND8BeKkANgAYADgA8etBk3IwKnYEgAqEQQDk0ANwB8tBUtVqAdAGUYYfLgg0t9OjpXr9ASXwwAtowowAZtxABiHhoA4jD4dADO%2BGgUzlBIAPSKdgZOrlbxiXpGJmYWaQm66hoAvuJ0AEYQFJQ%2BsJ5oAK4ANvhi1hG4YADWAJ60aehYeESGuLBlUeGjMOMyciOwenS1Dc3GjdkwUA5QPo24EQHa8zCZADIwajCNdGb46z4AwhAughYwNPhhh9ZIx5kpbkIHm8PH8IDoNHU2x8ZXq%2BHwFgCACE4QiaPE-vYAXlMQZzpdGjipnpipMxlEUI00GBXO8uDx1p4WiArAxSI1GhA6AB3SqNKCleIDHAEQjHGZ5YVDEjMaQaEBFIA)

![Screen Shot 2020-08-14 at 10 13 01 pm](https://user-images.githubusercontent.com/33337378/90248100-5a90bc80-de7b-11ea-9fde-df01343d6354.png)

**Describe the solution you'd like**

Maybe I'm missing something completely obvious, but it would be nice to have an example of how to use both successfully (i.e. how the docs site does it).

**Comment by jxom** [comment]
Maybe this one? https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8AFAhgcxgdQJYBcALACRjVgCcAdAOwAI7CzLTcND8BeKkANgAYADgA8etBk3IwKnYEgAqEQQDk0ANwB8tBUtVqAdAGUYYfLgg0t9OjpXr9ASXwwAtowowAZtxABiHhoA4jD4dADO%2BGgUzlBIAPSKdgZOrlbxiXpGJmYWaQm66hoAvuLhZmAA1gCetGnoWHhEhriwAEZR4S0w7TJyzbB6dLCeaACuADb4xuPZMFAOUD7juBEB2v0wmQAyMGow43Rm%2BDM%2BAMIQLoIWMDT4YWvWSBuZKW6EHt48-iB0NOoLPlao3w%2BAsAQAQsDQTR4s97K88nCDDs9uNEV09MVOm0oihxmgwK4blweDNPPgHgxSONxhA6AB3CAUcZQUrxeo4AiEDY9PIcxokZjSDQgIpAA
