### ISSUE TITLE
Show / Hide above/below

### ISSUE THREAD

**Issue by b-gibbs** [bumbag/bumbag-ui#44]
The Show and Hide components seem to respond to a breakpoint above or below the breakpoint supplied.

Open the page at https://bumbag.style/layout/show/ in Chrome. Show Developer Tools with a responsive layout. Change the width of the screen and watch when the message changes. The message should change at a width of 1024px - the desktop breakpoint, as described at https://bumbag.style/breakpoints/ . But, it changes at 768px, the tablet width.

I've seen the same behavior in my own app.

**Expected behavior**

The message should change at desktop width of 1024px.

![Screen Shot 2020-08-23 at 2 39 11 PM](https://user-images.githubusercontent.com/187297/90987167-977d4300-e54e-11ea-9b81-b35e736cbfee.png)

**Comment by jxom** [comment]
Thanks for the observation... This is now fixed on `1.1.7`, and the `above`/`below`-based breakpoint props now align to the breakpoint specified on https://bumbag.style/breakpoints
