### ISSUE TITLE
Group hover/focus pseudo-styles

### ISSUE THREAD

**Issue by hazem3500** [bumbag/bumbag-ui#45]
**Is your feature request related to a problem? Please describe.**

There isn't currently a direct way to style a child if its parent is hovered/focused on.

**Describe the solution you'd like**

We could implement the pseudo-styles like [tailwind pseudo-class-variants(group-hover & group-focus)](https://tailwindcss.com/docs/pseudo-class-variants#group-hover), it could have a similar API to chakra-ui [`_groupHover`](https://chakra-ui.com/pseudobox#group-hover)

I am willing to make a PR adding those pseudo-styles.

**Comment by jxom** [comment]
I think it would make sense to sync with Tailwind & Chakra with this. Feel free to raise a PR!
