### ISSUE TITLE
Menu with options

### ISSUE THREAD

**Issue by hazem3500** [bumbag/bumbag-ui#47]
**Is your feature request related to a problem? Please describe.**

It isn't clear how or there isn't a component yet to make a menu that contains options that could be selected
![menu with options](https://live.staticflickr.com/65535/50265605498_2e99ed30a3_o.png)

**Describe the solution you'd like**

If it's already possible with the current components we could add an example for it in the Docs, If it's not possible with the current set of components we could consider adding a component that handles this use-case.

**Comment by jxom** [comment]
I would say [SelectMenu](https://bumbag.style/form/select-menu/) might be what you are looking for... However, it doesn't have the ability to group sections yet...

**Comment by hazem3500** [comment]
[SelectMenu](https://bumbag.style/form/select-menu/) acts more like an input.
I was thinking more of a menu that works with a Button like the chakra-UI [Menu](https://bumbag.style/form/select-menu/)

**Comment by jxom** [comment]
Yeah true. Reakit exports a `MenuItemRadio` & `MenuItemCheckbox` component. So we could definitely make use of them. https://reakit.io/docs/menu/#menu-bar

**Comment by jxom** [comment]
Added in [1.2.0](https://github.com/bumbag/bumbag-ui/releases/tag/v1.2.0)
