### ISSUE TITLE
Menu & SelectMenu components scrolls page on focus in Docs

### ISSUE THREAD

**Issue by hazem3500** [bumbag/bumbag-ui#50]
**Describe the bug**

When clicking on Menu or SelectMenu component the page jumps to a place bottom of the component

**To Reproduce**
1. Go to https://bumbag.style/form/select-menu/ or https://bumbag.style/components/menu/
2. Click on any Menu or selectMenu component

**Expected behavior**

It should not scroll the page or scrolls to the component, not to the bottom of the page

**Screenshots**

![bug.gif](https://live.staticflickr.com/65535/50265686463_094f4f2dde_o.gif)

**Device information (please complete the following information):**

-   Device: Desktop
-   OS, version: Windows 10
-   Browser, version: Chrome v84.0.4147.135

**Comment by jxom** [comment]
This should be fixed now
