### ISSUE TITLE
Contributing Docs have broken links

### ISSUE THREAD

**Issue by hazem3500** [bumbag/bumbag-ui#53]
In the [CONTRIBUTING.md](https://github.com/bumbag/bumbag-ui/blob/master/CONTRIBUTING.md) file, the [Guide to developing a new component
](https://github.com/bumbag/bumbag-ui/blob/master/CONTRIBUTING.md#guide-to-developing-a-new-component) has broken links for all the realistic examples.

**Comment by jxom** [comment]
Whoops, I'll have to amend this. It's a bit old...
