### ISSUE TITLE
Can't specify width of Dialog footer

### ISSUE THREAD

**Issue by hazem3500** [bumbag/bumbag-ui#54]
**Describe the bug**

When passing a component with the prop `width="100%"` to `Dialog.Modal`'s `footer` prop, the footer still takes the width of the content of the passed component.

**To Reproduce**

1. pass `<Box width="100%" backgroundColor="primary">hello</Box>` to `Dialog.Modal`'s `footer` prop

**Expected behavior**

The passed component should take the full width of the footer

**Screenshots**

Playroom: [link](https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8BZaBDANgOgMoBd18YA%2BAHQDsACKpAEQEssIBzbNKLSmmgMwgjEATgF5gSAEIQAHlQDuDKPgAWIsiACMABi0BSdVQBG6MAGsWQiAFcKUAMIRMEUeoAOQhgFt0QgJ7qSZRhMJyQAeilpEgBfbh58BnxMGDUQABUYAGd8dTjyaipibLjwxmY2Dix8mlQMHEZMsCdMqyEYKitMlOAJK3x8CApo6p4AeVcYak86krDK%2BoZG5tbSSnD5vEJiEhBooA)

**Device information (please complete the following information):**

-   Device: Desktop
-   OS, version: Windows 10
-   Browser, version: Chrome v84.0.4147.135

**Comment by jxom** [comment]
Fixed on `1.1.15`
