### ISSUE TITLE
Customize spacing of ActionButtons

### ISSUE THREAD

**Issue by hazem3500** [bumbag/bumbag-ui#55]
**Is your feature request related to a problem? Please describe.**

When adding ActionButtons to a Dialog, I want to add a space-between the two buttons so the cancel button will be placed on the left of the footer and the primary button be placed on the right side of the footer.
**Example:**
![example.png](https://i.imgur.com/KHDoK0M.png)

**Describe the solution you'd like**

We should implement an API to be able to add space, space-out the two buttons.

**Describe alternatives you've considered**

I've tried using the normal `Button` components and the `footer` prop on `Dialog.Modal` but I had the same issue as #54 

Playroom: [link](https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8BZaBDANgOgMoBd18YA%2BAHQDsACKpAEQEssIBzbNKLSmmgMwgjEATgF5gSAGKYYADyoArAK4BnfA14BPAMIQKxPSLIhlAB3RgYAWgBGMfAHcYMCkar2GUfAAtDIAIwADAEApEYkSABCivj4uiRa6BQWmEgA9FExcZHRsdRm0jEwviZCDAC26EIaYToUvAxCZWkZueGpUrIkAL7cPGr40r4AKl4MylRjVOhU-dJGveTUPAAyEEIwZRMmyoqbUBCYa1TKDPhTZXYANFSQFMowYMT4ikJTUAwmY2AMFCxUMJhTtgqLgVCZnO9lPcqO90JsPjsytcwC8duMPFQTJhzDAhEQbroWIoYNdFJh8KULMpejQYCw7FRpI8VMC6IpJiYIDtcTBsL00oxmGwOFhFjRUBgcIxlGBDjt1lQVEVgC1dF0xTwAPLg6hlSX81IiqVfOUvUiUNJGvCEYgkEBdIA)

**Comment by jxom** [comment]
I think this would be related to #54, but it also would be nice to specify positioning of the ActionButtons too.

**Comment by jxom** [comment]
You can now space out `ActionButtons` by appending `justifyContent` and `width` props:
https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8BZaBDANgOgMoBd18YA%2BAHQDsACKpAEQEssIBzbNKLSmmgMwgjEATgF5gSAIJh8DCBQBCAV3z45AZyoArRWpm8AngGE5xCvhFkQagA7owMALQAjGPgDuMGBUtU3DKPgAFhYgAIwADOEApD4A9CQAvtw8MviYMCEAKoEMGrlU6FSp6ZbJ5NQ8ADIQQjAAtlQM1mqKDVAQmDVUagz4BXWuADRUkBRqMNKuikIFUE25YAwULFQwmL3YVLg61l5zauNUc%2BgNTS11w2DTLXlQVNaYdjBCRCNyLIoww4qY%2BEIM9jUyRoMBYrio6WkOk2dEU%2BWsEBazxg2GSSFijGYbA4WHKNFQGBwjDUYE6LVqVB0GWAShUcgSeJ4AHldtQ6oS0bEcUSFmTpqRKOjuXhCMQSCAEkA
