### ISSUE TITLE
SwitchGroup Horizontal alignment

### ISSUE THREAD

**Issue by hazem3500** [bumbag/bumbag-ui#57]
**Describe the bug**

The last switch in the SwitchGroup isn't aligned correctly when the orientation is horizontal 

**To Reproduce**

playroom: [link](https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8BlA7gSwC5gBYHEAnCAVwAcAdAOwAIaJCMYqsBDLDCKgXgpFwYYAXlzYAbPtTpVWAWxi8QaGO1wxCAJkm16ZDlwDO3YAG0pdGsBpjWAIxhj4NAOQoSVKgE9nAGhoA3VjESGCdnA3cvZxoAXx9zOisbe0cXAHUMKihvP0Dg0JdMLO9Y%2BJ1E6zsHMIB5f3UwVgMsXwCgkLCIesJG5uiY8wBdAaoAegA%2BEBigA)

**Expected behavior**

All switches to be aligned when the orientation is horizontal

**Comment by jxom** [comment]
Fixed on `1.1.13`
