### ISSUE TITLE
Autosuggest isn't focus-able after double-clicking on it

### ISSUE THREAD

**Issue by hazem3500** [bumbag/bumbag-ui#58]
**Describe the bug**

When double clicking `Autosuggest` it freezes and the user isn't able to search anymore

**To Reproduce**
1. Go to https://bumbag.style/form/autosuggest/
2. Double click on `Autosuggest`
3. Try to focus on the input to search

**Expected behavior**

I should be able to search or focus on the input after double-clicking

**Screenshots**

![issue.gif](https://live.staticflickr.com/65535/50271207886_6ef86c22bf_o.gif)

**Device information (please complete the following information):**

-   Device: Desktop
-   OS, version: Windows 10
-   Browser, version: Chrome v84.0.4147.135

**Comment by jxom** [comment]
Fixed on `1.1.12`
