### ISSUE TITLE
Textarea - make size adjustable

### ISSUE THREAD

**Issue by b-gibbs** [bumbag/bumbag-ui#59]
Please consider providing more flexibility to control the size of a Textarea component. Right now, sizes are provided, but setting size= small, medium or large affects both the height of the text area and the font size. I'd like to be able to specify the font size and the number of rows visible independently. This could be as simple as exposing the HTML "rows=". It would also be nice to be able to set the textarea so that it is not resizable by the user (get rid of handle in lower right), but still allows scrolling.

**Comment by jxom** [comment]
> This could be as simple as exposing the HTML "rows="
The `Textarea` component inherits the native `textarea` HTML element, meaning it does provide you with a `rows` prop. 

> It would also be nice to be able to set the textarea so that it is not resizable by the user
I tried to add the `resize` CSS prop, but it didn't seem to work. I'll have to add it in. For the meantime, you may need to use a styled component to achieve this:

```jsx
import { Textarea, applyTheme } from 'bumbag';
 
const CustomTextarea = applyTheme(Textarea, {
  styles: {
    base: {
      resize: 'none'
    }
  }
});

<CustomTextarea />
```

**Comment by b-gibbs** [comment]
> The `Textarea` component inherits the native `textarea` HTML element, meaning it does provide you with a `rows` prop.

Like this?

<img width="288" alt="Screen Shot 2020-12-15 at 9 56 42 AM" src="https://user-images.githubusercontent.com/187297/102238927-eebb7080-3ebb-11eb-86be-cff41ed05169.png">

**Comment by b-gibbs** [comment]
It's just a TypeScript error (Property "rows" does not exist on type...). The textarea does respond to changing row values.
