### ISSUE TITLE
Extraneous Box wrapper for Provider

### ISSUE THREAD

**Issue by kerryaustin** [bumbag/bumbag-ui#82]
Not quite sure if this is a bug, but it looks like there is a Box wrapper around the children supplied to the provider:

https://github.com/bumbag/bumbag-ui/blob/673b98af88534a0910d49e20fca40833a2f9d2d5/packages/bumbag/src/Provider/Provider.tsx#L62

Is there a reason for this? It make it challenging to set 100% / fill-available heights for content due to this wrapping box.

**Comment by jxom** [comment]
I can't remember the reasoning for this, I don't think we need it. Try updating to `1.3.21`.

**Comment by kerryaustin** [comment]
This seems top have popped up again, seeing this in: `1.11.6`
