### ISSUE TITLE
how can I size a Select Menu

### ISSUE THREAD

**Issue by samthomson** [bumbag/bumbag-ui#93]
I would like to size a select menu the same way I can size an input.

![image](https://user-images.githubusercontent.com/6588340/103482385-88e64880-4dd8-11eb-8d32-7db2e466bfdb.png)

In the above the text input has `size="small"`. I've tried adding that to the SelectMenu to no avail. 
I've also read through the props and theming section of the controls docs https://bumbag.style/form/select-menu

**Comment by shannonrothe** [comment]
Fix is in progress in #100 👍🏼

**Comment by jxom** [comment]
It will be in the next release 👌

**Comment by samthomson** [comment]
Excellent, thanks
