### ISSUE TITLE
Dialog content not opened inside portal

### ISSUE THREAD

**Issue by sam-chuang** [bumbag/bumbag-ui#96]
**Describe the bug**
At version 1.6.8, the dialog content opened inside portal, but after this [change](https://github.com/bumbag/bumbag-ui/commit/f3c243b7a3bc484aaa50297f1ce8ee2eeb3fa578), it doesn't open the content inside portal

**To Reproduce**
```
<Modal.State>
  <Modal.Disclosure use={Button}>Open modal</Modal.Disclosure>
  <Modal>
    <Card>
      <Box>Hello world</Box>
      <Modal.Disclosure use={Button}>Close</Modal.Disclosure>
    </Card>
  </Modal>
</Modal.State>
```
1. click Open modal button
2. open browser dev tool
3. check the reakit portal element, it only has modal backdrop, it doesn't has the dialog content inside

**Expected behavior**
The dialog content should be inside portal

**Screenshots**
now v1.6.10, content not inside portal
![content](https://user-images.githubusercontent.com/33828310/104142011-85fce080-53f4-11eb-804a-5b74e7171779.png)

expected v1.6.8, content inside portal
![expected](https://user-images.githubusercontent.com/33828310/104142089-e855e100-53f4-11eb-9472-de89b29846c1.png)

**Device information (please complete the following information):**
-   OS, version: windows 10
-   Browser, version: Chromium: 87

**Additional context**
not sure if [it's the cause](https://github.com/bumbag/bumbag-ui/blob/acf17f758ab87dc9a31a7595428525eeb143639e/packages/bumbag/src/Modal/Modal.tsx#L69-L81), but after I remove the wrapElement, the dialog content appear inside portal

**Comment by jxom** [comment]
Thanks for reporting! This should be fixed on `1.7.0`. Can you try again?
